### ISSUE TITLE
Dec-22-2020 Discussion and Follow-up

### ISSUE THREAD

**Issue by zsjjames** [LLNL/ISO-DART#6]
This issue is created as summary of Dec-22-2020 discussion and suggest follow-up action items.
The report with details of initial test at ANL side is online at: https://www.overleaf.com/read/gzmwxkkspxwh

Project team also suggested some action items, it would be great if we can follow-up on them :

- [x] 1. Project team will further discuss which data types are useful to this project and should be included in data repository. 

- [x] 2. For the Python Environment, do we need "python-levenshtein" package?

- [x] 3. For the CAISO data, is it possible we remove the sleep function to speed up data process and still be able to request data from CAISO?

- [x] 4. Certain days of certain dataset could not be extracted (details in report)

**Comment by sotorrio1** [comment]
Issues 2, 3 and 4 in the comment above were taken care of by PR #7

**Comment by sotorrio1** [comment]
Closing because task 1 no longer applies.
